//Q. Write a program to create a class called Employee, having instance
//        variables like name, age, salary and empno. Initialize all the
//        instance members using constructor and empno should be auto
//        generated by the program. Create an array of objects to define 10
//        Employees.

package Lab_Practicals;

public class practical_24 {
    public static void main(String[] args) {
        // Create an array of 10 Employee objects
        Employee[] employees = new Employee[10];
        employees[0] = new Employee("John", 30, 50000.0);
        employees[1] = new Employee("Alice", 28, 60000.0);
        // Add more employees as needed...

        // Display employee details
        System.out.println("Employee Details:");
        for (Employee emp : employees) {
            System.out.println("Emp No: " + emp.getEmpno());
            System.out.println("Name: " + emp.getName());
            System.out.println("Age: " + emp.getAge());
            System.out.println("Salary: $" + emp.getSalary());
            System.out.println();
        }
    }
    public static class Employee {
        private static int nextEmpNo = 1001; // Starting employee number
        private String name;
        private int age;
        private double salary;
        private int empno;

        // Constructor to initialize instance variables
        public Employee(String name, int age, double salary) {
            this.name = name;
            this.age = age;
            this.salary = salary;
            this.empno = nextEmpNo++; // Auto-generate employee number
        }

        // Getter methods
        public String getName() {
            return name;
        }

        public int getAge() {
            return age;
        }

        public double getSalary() {
            return salary;
        }

        public int getEmpno() {
            return empno;
        }
    }

}
